### ISSUE TITLE
Excess hex publishing?

### ISSUE THREAD

**Issue by antipax** [Cobenian/raygun#1]
Hi,

First of all, thanks for your hard work on this package, I am sure it will be very useful for a lot of people!

I've noticed you're publishing many versions of this package to hex.pm -- I'm not a member of the hex team, but it seems like it might be a bit excessive. :)

Instead of publishing the package for each small change you make, you could instead use either: `{:raygun, path: "../path/to/raygun"}` or `{:raygun, github: "Cobenian/raygun"}` in your mix.exs and avoid having to publish so many versions. I am, of course, assuming that you are publishing the versions in order to test them in a consuming application.

Of course, you are well within your right to publish as many versions as you wish, so please do continue if you disagree, and thanks again for your contribution to the Elixir ecosystem!

**Comment by brweber2** [comment]
Thanks for the tips. You guessed correctly that we're testing this with a client. It is a remote client so the path option wouldn't work for us (although I might modify out setup just to test this). I wasn't aware that the second option would pull the latest changes every time. I'll go ahead and finish testing locally to get this macro working and then publish the working version. 

Just out of curiosity, how did you see this?  The recently updated section on hex.pm?

Probably the politest request I've ever received on the internet. Thanks for that! :)

**Comment by antipax** [comment]
The second option won't pull the latest changes every time, but if you run `mix deps.update raygun` each time you update the github repo, it will.

Yep, I check the recently updated section to keep up to date with what's happening in the Hex world.

No problem, just pay it forward! :)
