### ISSUE TITLE
Timex dependency

### ISSUE THREAD

**Issue by smdern** [Cobenian/raygun#24]
Elixir 1.3 added Calendar structs which Timex 3.0+ takes advantage of. Is there any plan on releasing a new semver that uses `~> timex 3.0` ?

**Comment by smdern** [comment]
Looks like `timex` is used in a single place, which means it could be removed as a dependency all together. 

https://github.com/Cobenian/raygun/blob/f5f9596f9c610a7b6f95d847dd4920f2bb0ee9c7/lib/raygun/format.ex#L138

could be converted to just `DateTime.utc_now |> DateTime.to_iso8601`

**Comment by smdern** [comment]
https://github.com/Cobenian/raygun/pull/25

**Comment by brweber2** [comment]
Merged the pull request. Closing.
