### ISSUE TITLE
Add Exilir docs to Raygun's public documentation site 

### ISSUE THREAD

**Issue by sumitramanga** [Cobenian/raygun#35]
Hi there,

I wanted to check if this is still a working module with Raygun for Elixir projects?  I work at Raygun and have been in my spare searching around to see what the community has built :) I think it's pretty awesome this exist but I wanted to know if this is a working repo for any Exilir app. I'd love to add this to our public documentation if it is. We will add credit to this repo if that happens! Or if there is some tidy up to do, I'd be keen to discuss what's left before shouting out. 

Looking forward to your response!

Kind regards,
Sumitra

**Comment by brweber2** [comment]
We used to use this module for some applications of ours in production, however we no longer use it. I know that a few other people were using it as well. 

I have not tried it in several years so it may or may not work with the current version of Raygun. My assumption is that most likely some small changes are needed to adjust for any changes to Raygun's API in the past few years. 

Thank you for reaching out.

**Comment by sumitramanga** [comment]
Hi @brweber2 !

Thanks so much for getting back to me. I saw there's a fork with recent changes. I may reach out to them to see.

Kind regards,
Sumitra

**Comment by sumitramanga** [comment]
We managed to get some docs in using one of the forks which are more up to date! We can close this issue out now. Thank you for your contributions on starting this Elixir client @brweber2 !! 🌟 We really appreciate it
